// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package trackingcoin

import (
	"database/sql"
)

type Asset struct {
	ID                int32
	CmcID             int64
	Name              string
	Slug              string
	Price             float64
	PercentChange1h   float32
	PercentChange24h  float32
	PercentChange7d   float32
	MarketCap         float64
	Volume24h         float64
	CirculatingSupply float32
	AllTimeHigh       float32
	AllTimeLow        float32
	Turnover          float32
	TotalSupply       float32
	MaxSupply         float32
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type User struct {
	ID             int32
	Email          string
	Fullname       string
	HashedPassword string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}
