// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/augustus281/trackingcoin/internal/handler/auth"
	"github.com/augustus281/trackingcoin/internal/repository/user"
	"github.com/augustus281/trackingcoin/internal/service/auth"
)

// Injectors from user_wire.go:

func InitAuthRouterHandler() (*auth.AuthHandler, error) {
	iUserRepository := repository.NewUserRepo()
	iAuthService := service.NewAuthService(iUserRepository)
	authHandler := auth.NewAuthHandler(iAuthService)
	return authHandler, nil
}
