// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	handler2 "github.com/augustus281/trackingcoin/internal/handler/auth"
	"github.com/augustus281/trackingcoin/internal/handler/coinmarketcap"
	"github.com/augustus281/trackingcoin/internal/repository/coinmarketcap"
	repository2 "github.com/augustus281/trackingcoin/internal/repository/user"
	service2 "github.com/augustus281/trackingcoin/internal/service/auth"
	"github.com/augustus281/trackingcoin/internal/service/coinmarketcap"
)

// Injectors from cmc_wire.go:

func InitCMCRouterHandler() (*handler.CMCHandler, error) {
	icmcRepository := repository.NewCMCRepo()
	icmcService := service.NewCMCService(icmcRepository)
	cmcHandler := handler.NewCMCHandler(icmcService)
	return cmcHandler, nil
}

// Injectors from user_wire.go:

func InitAuthRouterHandler() (*handler2.AuthHandler, error) {
	iUserRepository := repository2.NewUserRepo()
	iAuthService := service2.NewAuthService(iUserRepository)
	authHandler := handler2.NewAuthHandler(iAuthService)
	return authHandler, nil
}
